[tool.poetry]
name = "frd2vtu"
version = "0.1.3"
description = "converter from calculix binary frd to vtu"
authors = ["wr1 <8971152+wr1@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9.7"
pyvista = ">=0.43.1, <=0.44.2"
vtk = "^9.3.0"
pandas = "^2.2.0"
numpy = ">2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
frd2vtu = "frd2vtu.frd2vtu:main"
frd2vtu_plot = "frd2vtu.basic_plot:main"
