[tool.poetry]
name = "frd2vtu"
version = "0.1.1rc6"
description = "converter from calculix frd to vtu"
authors = ["wr1 <8971152+wr1@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9.7"
fire = "^0.7.0"
pyvista = "^0.43.5"
vtk = "^9.3.0"
pandas = "^2.2.1"
numpy = "1.26.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
frd2vtu = "frd2vtu.frd2vtu:main"
frd2vtu_plot = "frd2vtu.basic_plot:main"